name: Build App

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Publish app
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v22

      - name: Build app
        run: nix develop --command trunk build --release

      - name: Deploy app
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          cname: fedimint-leptos.sirion.io
